version: '3.8'

services:
  postgres:
    container_name: budgeter_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    ports:
      - "5432:5432"
    volumes:
      - db:/postgres/data
    restart: always

volumes:
    db:
      driver: local